---
- name: test awx api
  hosts: localhost

  vars_files:
    - users.yml

  tasks:
    - name: check if can do basic things
      ansible.controller.ad_hoc_command:
        inventory: Demo Inventory
        credential: Demo Credential
        module_name: command
        module_args: echo Hallo Welt
        wait: true
      register: hallo

    - ansible.builtin.debug: var=hallo

    - name: Create dev team
      ansible.controller.team:
        name: Instructors
        description: Course instructors
        state: present
        organization: Default

    - name: Create users 
      ansible.controller.user:
        first_name: "{{ item['first_name'] }}"
        last_name: "{{ item['last_name'] }}"
        username: "{{ item['username'] }}"
#        password: "{{ item['password'] }}"
        auditor: "{{ item['auditor'] }}"
        superuser: "{{ item['superuser'] }}"
        email: "{{ item['email'] }}"
        organization: "{{ item['organization'] }}"
      loop: "{{ users }}"

    - name: Create credential for SCM
      ansible.controller.credential:
        name: Automatic SCM credential
        organization: Default
        state: present
        credential_type: Source Control
        inputs:
          username: student
          ssh_key_data: "{{ lookup('file', '~/.ssh/gitlab_rsa') }}"

    - name: Create instructor project
      ansible.controller.project:
        name: Instructors
        description: Project for instructor stuff
        organization: Default
        state: present
        scm_type: git
        scm_url: 'git@github.com:kareiva/do467.git'
