---
- name: test awx api
  hosts: localhost

  vars:
    debug: False
    aap_version: 2.2

  vars_files:
    - user_vars.yml

  tasks:
    - ansible.builtin.debug: var=aap_version

    - name: check if can do basic things
      ansible.builtin.include_tasks: ad_hoc_command.yml
      tags:
        - debug
        - never

    - name: Create dev team
      ansible.builtin.include_tasks: team.yml
      tags:
        - team

    - name: Create users 
      ansible.builtin.include_tasks: user.yml
      tags: 
        - user

    - name: Create credential for SCM
      ansible.builtin.include_tasks: credential.yml
      tags:
        - credential

    - name: Create instructor project
      ansible.builtin.include_tasks: project.yml
      tags:
        - project

    - name: Create instructor inventory
      ansible.builtin.include_tasks: inventory.yml
      tags:
        - inventory

    - name: Create instructor inventory source
      ansible.builtin.include_tasks: inventory_source.yml
      tags:
        - inventory_source

    - name: Create host in inventory
      ansible.builtin.include_tasks: host.yml
      tags:
        - host

    - name:  Change AAP settings
      ansible.builtin.include_tasks: settings.yml
      tags:
        - settings

    - name: Create instructor job template
      ansible.builtin.include_tasks: job_template.yml
      tags:
        - job_template

    - name: Create schedule for instructor job template
      ansible.builtin.include_tasks: schedule.yml
      tags:
        - schedule

    - name: Create workflow instructor job template
      ansible.builtin.include_tasks: workflow_job_template.yml
      tags:
        - workflow_job_template

